# Set some sane defaults for the rocon_authoring launch environment
ROCON_COMPOSER_BLOCKLY_MONGO_URL=mongodb://localhost:27017/rocon_authoring
ROCON_COMPOSER_BLOCKLY_SERVER_PORT=9999
MSG_DATABASE=http://61.43.117.202:10000
ROCON_COMPOSER_BLOCKLY_LOG_LEVEL=info
  
#Exports
export ROCON_COMPOSER_BLOCKLY_MONGO_URL
export ROCON_COMPOSER_BLOCKLY_SERVER_PORT
export MSG_DATABASE
export ROCON_COMPOSER_BLOCKLY_LOG_LEVEL
